version: '3.9'

# Network
networks:
  web_network:
    name: reactvitelayout
    driver: bridge

services:
  # React App Service
  reactapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_vite_layout
    restart: always
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - web_network